[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
common = { path = "../common" }
futures-util = { workspace = true }
tokio = { workspace = true }
zbus = { workspace = true }
