[workspace]
resolver = "3"
members = [ "server", "client" , "common"]

[workspace.dependencies]
anyhow = "1"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
